import {requireUser} from '@/lib/server/auth';
import {AppError,db,digest,errorResponse,json,sameOrigin} from '@/lib/server/runtime';
import {fileFor,owned,view} from '@/lib/server/records';
import {extract} from '@/lib/server/extraction';
import {contracts,createOnPlatform,mapBody,platformSession,allTargets} from '@/lib/server/platforms';
import {Extraction,minimumFields,overall,validate} from '@/lib/domain';
export async function POST(req:Request,{params}:{params:Promise<{id:string}>}){let id='',owner='',locked=false,lease=0;try{sameOrigin(req);owner=await requireUser(req);id=(await params).id;const r=await owned(id,owner);if(r.status==='complete')return json({record:await view(r)});lease=Date.now()+15*60000;const claimed=await db().prepare('UPDATE records SET lock_until=? WHERE id=? AND owner=? AND lock_until<=?').bind(lease,id,owner,Date.now()).run();if(!claimed.meta.changes)throw new AppError('Bu talimat halen işleniyor. Lütfen bekleyin.',409);locked=true;const {results:deliveries}=await db().prepare('SELECT * FROM deliveries WHERE record_id=?').bind(id).all<{id:string;platform:string;status:string;idempotency_key:string}>();if(deliveries.some(d=>['unknown','sending'].includes(d.status)))throw new AppError('Önceki aktarımın sonucu doğrulanmalı. Mükerrer kayıt oluşmaması için yeniden gönderim durduruldu.',409);await db().prepare("UPDATE records SET status='processing' WHERE id=?").bind(id).run();const ex:Extraction=r.extraction?JSON.parse(r.extraction):await extract(await (await fileFor(r)).arrayBuffer(),r.filename,r.mime);const configured=contracts();const requirements=[...minimumFields,...configured.flatMap(c=>c.create?.requiredFields||[])];const issues=validate(ex,requirements);await db().prepare('UPDATE records SET fields=?,extraction=?,issues=?,status=?,updated_at=? WHERE id=?').bind(JSON.stringify(ex.fields),JSON.stringify(ex),JSON.stringify(issues),issues.length?'missing':'ready',new Date().toISOString(),id).run();if(issues.length)return json({record:await view(await owned(id,owner))});
 // Preflight EVERY pending platform before creating anything. Unknown schemas never receive writes.
 const pending=allTargets().filter(t=>deliveries.find(d=>d.platform===t.id)?.status!=='created');const prepared=[];for(const t of pending){const c=configured.find(c=>c.id===t.id);if(!c?.verified)throw new AppError(`${t.name} / ${t.kind}: kayıt servisi ve alan eşlemesi doğrulanmayı bekliyor.`,503);if(ex.containers.length>1&&!JSON.stringify(c.create.body).includes('containers'))throw new AppError(`${c.name}: çoklu konteyner eşlemesi doğrulanmalı.`,503);if(ex.cargoLines.length>1&&!JSON.stringify(c.create.body).includes('cargoLines'))throw new AppError(`${c.name}: çoklu mal kalemi eşlemesi doğrulanmalı.`,503);const businessKey=await digest(JSON.stringify([ex.fields.bookingNumber.value,ex.containers.map(x=>x.containerNumber.value).sort(),t.kind]));const duplicate=await db().prepare('SELECT record_id FROM deliveries WHERE owner=? AND platform=? AND business_key=? AND record_id<>?').bind(owner,t.id,businessKey,id).first();if(duplicate)throw new AppError(`${t.name}: bu booking ve konteyner için başka bir kayıt mevcut. Önceki kaydı kullanın.`,409);const session=await platformSession(c,owner);const payload=mapBody(c.create.body,ex.fields,ex);prepared.push({c,session,payload,businessKey,delivery:deliveries.find(d=>d.platform===t.id)!});}
 for(const x of prepared){const claim=await db().prepare("UPDATE deliveries SET status='sending',payload=?,updated_at=?,owner=?,business_key=? WHERE id=? AND status IN ('waiting','failed','blocked')").bind(JSON.stringify(x.payload),new Date().toISOString(),owner,x.businessKey,x.delivery.id).run();if(!claim.meta.changes)continue;const result=await createOnPlatform(x.c,x.session,x.payload,x.delivery.idempotency_key);await db().prepare('UPDATE deliveries SET status=?,reference=?,message=?,updated_at=? WHERE id=?').bind(result.status,result.reference||null,result.message,new Date().toISOString(),x.delivery.id).run();}
 const statuses=await db().prepare('SELECT status FROM deliveries WHERE record_id=?').bind(id).all<{status:string}>();await db().prepare('UPDATE records SET status=? WHERE id=?').bind(overall(statuses.results),id).run();return json({record:await view(await owned(id,owner))});
 }catch(e){if(locked){const issue=e instanceof AppError?e.message:'İşlem tamamlanamadı. Platforma aktarım sonucunu kontrol edin.';await db().prepare("UPDATE records SET status=CASE WHEN EXISTS(SELECT 1 FROM deliveries WHERE record_id=? AND status IN ('sending','unknown')) THEN 'unknown' ELSE 'blocked' END,issues=? WHERE id=?").bind(id,JSON.stringify([issue]),id).run();}return errorResponse(e)}finally{if(locked)await db().prepare('UPDATE records SET lock_until=0 WHERE id=? AND owner=? AND lock_until=?').bind(id,owner,lease).run()}}
