import {transfer} from '@/lib/server/transfer';
import {applyManual} from '@/lib/manual-extraction';
import {emptyManual,manualIssues,manualSchema} from '@/lib/manual';
import {requireUser} from '@/lib/server/auth';
import {AppError,db,digest,errorResponse,json,sameOrigin} from '@/lib/server/runtime';
import {sourceFiles,owned,view} from '@/lib/server/records';
import {extractDocuments} from '@/lib/server/extraction';
import {contracts} from '@/lib/server/platforms';
import {Extraction,minimumFields,validate} from '@/lib/domain';
export async function POST(req:Request,{params}:{params:Promise<{id:string}>}){let id='',owner='',locked=false,lease=0;try{sameOrigin(req);owner=await requireUser(req);id=(await params).id;const r=await owned(id,owner);if(r.status==='complete')return json({record:await view(r)});lease=Date.now()+15*60000;const claimed=await db().prepare('UPDATE records SET lock_until=? WHERE id=? AND owner=? AND lock_until<=?').bind(lease,id,owner,Date.now()).run();if(!claimed.meta.changes)throw new AppError('Bu talimat halen işleniyor. Lütfen bekleyin.',409);locked=true;const {results:deliveries}=await db().prepare('SELECT * FROM deliveries WHERE record_id=?').bind(id).all<{id:string;platform:string;status:string;idempotency_key:string}>();if(deliveries.some(d=>['unknown','sending'].includes(d.status)))throw new AppError('Önceki aktarımın sonucu doğrulanmalı. Mükerrer kayıt oluşmaması için yeniden gönderim durduruldu.',409);const uncertain=await db().prepare("SELECT step FROM platform_steps WHERE record_id=? AND status IN ('sending','unknown') LIMIT 1").bind(id).first();if(uncertain)throw new AppError('Önceki platform adımı doğrulanmalı; tekrar gönderim durduruldu.',409);await db().prepare("UPDATE records SET status='processing' WHERE id=?").bind(id).run();let ex:Extraction=r.extraction?JSON.parse(r.extraction):await extractDocuments(await sourceFiles(r));const sourceExtraction=structuredClone(ex);const manual=manualSchema.parse(r.manual?JSON.parse(r.manual):emptyManual);ex=applyManual(ex,manual);const configured=contracts();const requirements=[...minimumFields,...configured.flatMap(c=>c.create?.requiredFields||[])];const issues=[...validate(ex,requirements),...manualIssues(manual)];await db().prepare('UPDATE records SET fields=?,extraction=?,issues=?,status=?,updated_at=? WHERE id=?').bind(JSON.stringify(ex.fields),JSON.stringify(sourceExtraction),JSON.stringify(issues),issues.length?'missing':'ready',new Date().toISOString(),id).run();if(issues.length)return json({record:await view(await owned(id,owner))});
 await transfer({id,owner,revision:r.revision},ex,manual,deliveries);return json({record:await view(await owned(id,owner))});
 }catch(e){if(locked){const issue=e instanceof AppError?e.message:'İşlem tamamlanamadı. Platforma aktarım sonucunu kontrol edin.';await db().prepare("UPDATE records SET status=CASE WHEN EXISTS(SELECT 1 FROM deliveries WHERE record_id=? AND status IN ('sending','unknown')) OR EXISTS(SELECT 1 FROM platform_steps WHERE record_id=records.id AND status IN ('sending','unknown')) THEN 'unknown' ELSE ? END,issues=? WHERE id=?").bind(id,e instanceof AppError&&e.status===422?'missing':'blocked',JSON.stringify([issue]),id).run();}return errorResponse(e)}finally{if(locked)await db().prepare('UPDATE records SET lock_until=0 WHERE id=? AND owner=? AND lock_until=?').bind(id,owner,lease).run()}}
