import {Fields,Extraction} from '../domain';
import {AppError,db,runtime} from './runtime';
export type Contract={id:string;name:string;kind:string;verified:boolean;authVerified?:boolean;allowInsecureHttp?:boolean;origin:string;auth:{type:'tmaxx'|'json';path:string;templatePath?:string;body:Record<string,unknown>;tokenPath:string;cookieRequired?:boolean};create:{path:string;method:'POST'|'PUT';body:unknown;requiredFields:string[];successPath:string;successValue:unknown;referencePath:string;idempotencyHeader?:string};lookup?:{path:string;referencePath:string;matches:Record<string,string>};};
export const targets=[{id:'tmaxx',name:'T-MAXX',kind:'HBL'},{id:'inttra',name:'INTTRA',kind:'MBL talimatı'}];
export function contracts():Contract[]{try{const c=JSON.parse(runtime().PLATFORM_CONTRACTS||'[]');if(!Array.isArray(c))throw 0;return c;}catch{throw new AppError('Platform bağlantı ayarları geçersiz.',503)}}
export function getPath(value:unknown,path:string):unknown{return path.split('.').reduce((a:unknown,k)=>a&&typeof a==='object'?(a as Record<string,unknown>)[k]:undefined,value)}
function url(c:Contract,path:string){const base=new URL(c.origin);if(base.protocol!=='https:'&&!(c.allowInsecureHttp&&c.id==='tmaxx'&&base.origin==='http://95.216.243.19:8090'))throw new AppError(`${c.name}: güvenli HTTPS servis adresi gerekli.`,503);const u=new URL(path,base);if(u.origin!==base.origin||!path.startsWith('/')||path.startsWith('//'))throw new AppError('Platform servis adresi geçersiz.',503);return u.toString()}
function checkContract(c:Contract){if(!c.verified||!c.create?.successPath||!c.create.referencePath||!c.create.requiredFields?.length||!c.auth?.tokenPath)throw new AppError(`${c.name}: oturum ve kayıt şeması doğrulanmayı bekliyor.`,503)}
export function mapBody(value:unknown,fields:Fields,ex?:Extraction):unknown{if(value&&typeof value==='object'&&!Array.isArray(value)&&'$each' in value){const v=value as {$each:string;template:unknown};if(!ex||!['containers','cargoLines'].includes(v.$each))throw new AppError('Tekrarlanan alan eşlemesi geçersiz.');return ex[v.$each as 'containers'|'cargoLines'].map(row=>mapBody(v.template,row,ex));}if(typeof value==='string'&&value.startsWith('$field:')){const key=value.slice(7);const f=fields[key];if(!f?.value||!f.source||f.confidence<.95)throw new AppError(`Aktarım alanı doğrulanamadı: ${key}`);return f.value;}if(typeof value==='string'&&value.startsWith('$number:')){const key=value.slice(8);const f=fields[key];if(!f?.value||!/^\d+(\.\d+)?$/.test(f.value)||!f.source||f.confidence<.95)throw new AppError(`Sayısal alan doğrulanamadı: ${key}`);return Number(f.value);}if(Array.isArray(value))return value.map(v=>mapBody(v,fields,ex));if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,mapBody(v,fields,ex)]));return value;}
function secretBody(value:unknown,credentials?:{username:string;password:string}):unknown{if(value==='$credential:username')return credentials?.username;if(value==='$credential:password')return credentials?.password;if(typeof value==='string'&&value.startsWith('$env:')){const result=(runtime() as unknown as Record<string,unknown>)[value.slice(5)];if(!result)throw new AppError('Platform giriş bilgileri eksik.',503);return result;}if(Array.isArray(value))return value.map(v=>secretBody(v,credentials));if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,secretBody(v,credentials)]));return value;}
async function encryptionKey(){const raw=runtime().ENCRYPTION_KEY;if(!raw||!/^[0-9a-f]{64}$/i.test(raw))throw new AppError('Oturum şifreleme anahtarı eksik.',503);return crypto.subtle.importKey('raw',new Uint8Array(raw.match(/../g)!.map(h=>parseInt(h,16))),'AES-GCM',false,['encrypt','decrypt'])}
async function seal(data:unknown){const iv=crypto.getRandomValues(new Uint8Array(12));const out=await crypto.subtle.encrypt({name:'AES-GCM',iv},await encryptionKey(),new TextEncoder().encode(JSON.stringify(data)));return JSON.stringify({iv:Array.from(iv),body:Array.from(new Uint8Array(out))})}
async function unseal(data:string){const {iv,body}=JSON.parse(data);return JSON.parse(new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:new Uint8Array(iv)},await encryptionKey(),new Uint8Array(body))))}
function cookies(r:Response){return (r.headers.getSetCookie?.()||[]).map(c=>c.split(';')[0]).join('; ')}
export async function fetchJson(endpoint:string,options:RequestInit){if(endpoint==='https://api.inttra.e2open.com/auth'&&runtime().INTTRA_RELAY_URL){const relay=new URL(runtime().INTTRA_RELAY_URL!);if(relay.protocol!=='https:'||relay.username||relay.password||!runtime().INTTRA_RELAY_KEY)throw new AppError('INTTRA bağlantı sunucusu ayarları eksik.',503);endpoint=new URL('/auth',relay).toString();options={...options,headers:{'Content-Type':'application/json',Authorization:'Bearer '+runtime().INTTRA_RELAY_KEY}};}const response=new URL(endpoint).origin==='http://95.216.243.19:8090'?await (await import('./tmaxx-transport')).tmaxxRequest(endpoint,options):await fetch(endpoint,{...options,redirect:'manual',signal:AbortSignal.timeout(25000)});if(!response.ok){const raw=(await response.text()).slice(0,16384);const edgeCode=raw.match(/error\s*(?:code\s*:?\s*)?(1003|1006|1010|1015|1020)\b/i)?.[1];const originIssue=/invalid cors request/i.test(raw);const server=(response.headers.get('server')||'').replace(/[^a-zA-Z0-9 ._-]/g,'').slice(0,40);throw new AppError(`Platform isteği tamamlanamadı (HTTP ${response.status}${edgeCode?'; ağ hata kodu '+edgeCode:''}${originIssue?'; kaynak adresi reddedildi':''}${server?'; yanıt sunucusu: '+server:''}).`,502);}if(!response.headers.get('content-type')?.includes('json'))throw new AppError('Platform JSON yerine farklı bir yanıt döndürdü.',502);return {response,data:await response.json()};}
export async function platformSession(c:Contract,owner:string,force=false):Promise<{token:string;cookie:string}>{if(!(c.authVerified||c.verified)||!c.auth?.tokenPath)throw new AppError(`${c.name}: giriş servisi henüz doğrulanmadı.`,503);const credentials=await readCredentials(owner,c.id);const key=owner+':'+c.id;const existing=await db().prepare('SELECT encrypted FROM platform_sessions WHERE key=? AND expires>?').bind(key,Date.now()).first<{encrypted:string}>();if(existing&&!force)return unseal(existing.encrypted);let cookie='',template={};if(c.auth.templatePath){const r=await fetchJson(url(c,c.auth.templatePath),{method:'GET'});template=r.data as object;cookie=cookies(r.response)}const r=await fetchJson(url(c,c.auth.path),{method:'POST',headers:{'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},body:JSON.stringify({...template,...secretBody(c.auth.body,credentials) as object})});const token=getPath(r.data,c.auth.tokenPath);if(typeof token!=='string'||!token)throw new AppError(`${c.name}: oturum doğrulanamadı. Ek doğrulama gerekebilir.`,502);cookie=[cookie,cookies(r.response)].filter(Boolean).join('; ');if(c.id==='inttra'){const webCookie=getPath(r.data,'webCookie');if(typeof webCookie==='string')cookie=webCookie;}if(c.auth.cookieRequired&&!cookie)throw new AppError(`${c.name}: gerekli oturum çerezi alınamadı.`,502);const session={token,cookie};await db().prepare('INSERT INTO platform_sessions (key,encrypted,expires) VALUES (?,?,?) ON CONFLICT(key) DO UPDATE SET encrypted=excluded.encrypted,expires=excluded.expires').bind(key,await seal(session),Date.now()+10*60000).run();return session}
export function allTargets(){return [...targets,...contracts().filter(c=>!targets.some(t=>t.id===c.id)).map(c=>({id:c.id,name:c.name,kind:c.kind}))]}
export async function readCredentials(owner:string,id:string):Promise<{username:string;password:string}|undefined>{const row=await db().prepare('SELECT encrypted FROM platform_credentials WHERE key=?').bind(owner+':'+id).first<{encrypted:string}>();return row?unseal(row.encrypted):undefined;}
export async function saveCredentials(owner:string,id:string,username:string,password:string){if(!allTargets().some(t=>t.id===id))throw new AppError('Platform bulunamadı.',404);if(!username.trim()||username.length>256||!password||password.length>1024)throw new AppError('Kullanıcı adı ve şifre gerekli.');await db().batch([db().prepare('INSERT INTO platform_credentials (key,encrypted) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET encrypted=excluded.encrypted').bind(owner+':'+id,await seal({username:username.trim(),password})),db().prepare('DELETE FROM platform_sessions WHERE key=?').bind(owner+':'+id)]);}
export async function connectionStates(owner:string){const configured=contracts();return Promise.all(allTargets().map(async t=>{const credentials=await readCredentials(owner,t.id);const base={...t,credentialsSaved:!!credentials,username:credentials?.username||''};const c=configured.find(c=>c.id===t.id);if(!c)return {...base,connected:false,message:credentials?'Giriş bilgileri kaydedildi. Platformun giriş servisi henüz doğrulanmadığı için bağlantı kurulamadı.':'Kullanıcı adı ve şifrenizi girerek platform bağlantısını kurun.'};try{await platformSession(c,owner,true);return {...base,connected:true,message:c.verified?'Platformda oturum açıldı.':'Platformda oturum açıldı. Konşimento aktarım servisi henüz doğrulanmadı.'}}catch(e){return {...base,connected:false,message:e instanceof AppError?e.message:'Platform bağlantısı kurulamadı.'}}}))}
export async function createOnPlatform(c:Contract,session:{token:string;cookie:string},payload:unknown,idempotencyKey:string):Promise<{status:string;reference?:string;message:string}>{checkContract(c);let attempted=false;try{const endpoint=url(c,c.create.path);const headers:Record<string,string>={'Content-Type':'application/json',Authorization:`Bearer ${session.token}`};if(session.cookie)headers.Cookie=session.cookie;if(c.create.idempotencyHeader)headers[c.create.idempotencyHeader]=idempotencyKey;attempted=true;const r=await fetch(endpoint,{method:c.create.method,headers,body:JSON.stringify(payload),redirect:'manual',signal:AbortSignal.timeout(30000)});if(!r.ok){if([400,401,403,404,422].includes(r.status))return {status:'failed',message:`Platform kaydı kabul etmedi (HTTP ${r.status}).`};return {status:'unknown',message:`Platform sonucu belirsiz (HTTP ${r.status}). Tekrar göndermeden mevcut kayıt kontrol edilmeli.`}}const body=await r.json();const success=getPath(body,c.create.successPath)===c.create.successValue;const ref=getPath(body,c.create.referencePath);if(!success||!(typeof ref==='string'||typeof ref==='number')||!String(ref))return {status:'unknown',message:'Yanıt alındı ancak kayıt referansı ve başarı sonucu doğrulanamadı. Tekrar gönderim durduruldu.'};return {status:'created',reference:String(ref),message:'Platform kaydı başarıyla oluşturdu.'}}catch{return {status:attempted?'unknown':'failed',message:attempted?'İstek sonrası yanıt doğrulanamadı. Mükerrer kayıt oluşmaması için tekrar gönderim durduruldu.':'Kayıt isteği hazırlanamadı.'}}}

export async function reconcile(c:Contract,owner:string,fields:Fields){if(!c.lookup?.path||!c.lookup.referencePath||!Object.keys(c.lookup.matches||{}).length)throw new AppError('Platformda kayıt sorgulama servisi henüz doğrulanmadı.',503);const session=await platformSession(c,owner);const path=c.lookup.path.replace(/\{([a-zA-Z0-9]+)\}/g,(_,key)=>{const v=fields[key]?.value;if(!v)throw new AppError('Sorgulama referansı eksik.');return encodeURIComponent(v)});const r=await fetchJson(url(c,path),{method:'GET',headers:{Authorization:`Bearer ${session.token}`,...(session.cookie?{Cookie:session.cookie}:{})}});for(const [responsePath,key] of Object.entries(c.lookup.matches)){if(String(getPath(r.data,responsePath))!==fields[key]?.value)throw new AppError('Platform yanıtı bu talimatla eşleşmiyor. Kayıt doğrulanmadı.',409)}const reference=getPath(r.data,c.lookup.referencePath);if(!reference||!['string','number'].includes(typeof reference))throw new AppError('Platform kaydı bulunamadı veya referansı doğrulanamadı.',409);return String(reference);}
