import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import ts from 'typescript';
const compile=s=>'data:text/javascript;base64,'+Buffer.from(ts.transpileModule(s,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText).toString('base64');
globalThis.__inttraOptions=await import(compile(fs.readFileSync('lib/inttra-options.ts','utf8')));
const {mapInttraManual}=await import(compile(fs.readFileSync('lib/inttra-mapping.ts','utf8').replace("import {chargeTypes,moveTypes,payerTypes} from './inttra-options';",'const {chargeTypes,moveTypes,payerTypes}=globalThis.__inttraOptions;')));
const input={bookingNumber:'TEST-BOOKING',blReference:'TEST-BL',vessel:'TEST VESSEL',voyage:'TEST VOYAGE',moveType:'1',chargeMode:'individual',charges:[{chargeType:'3',freightTerm:'Collect',payer:'4',paymentLocation:''}]};
test('manual choices use captured INTTRA codes without reusing shipment IDs',()=>{const p=mapInttraManual(input);assert.equal(p.PaymentInstructions.IndividualCharges_0.FreightTermCode,'1');assert.equal(p.PaymentInstructions.IndividualCharges_0.PartyName,'Consignee');assert.equal(p.SIReferences.CarrierBookingNumber.CarrierBookingNumber_1.ReferenceValue,'TEST-BOOKING');assert.equal(p.SIReferences.BLReferenceNumber.BLReferenceNumber_1.ReferenceValue,'TEST-BL');assert.equal(p.SiId,undefined);assert.equal(input.charges[0].payer,'4')});
test('unresolved location and invalid selections cannot silently produce wrong payloads',()=>{assert.equal(mapInttraManual({...input,chargeMode:'all'}).PaymentInstructions.ALLCharges.ChargeTypeCode,'6');assert.throws(()=>mapInttraManual({...input,charges:[{...input.charges[0],paymentLocation:'London'}]}));assert.throws(()=>mapInttraManual({...input,charges:[{...input.charges[0],payer:'unknown'}]}))});

test('House Bill reference uses user input and never sample shipment number',()=>{assert.equal(mapInttraManual(input).SIReferences.HouseBillNumber,undefined);assert.equal(mapInttraManual({...input,houseBillNumber:'USER-HBL'}).SIReferences.HouseBillNumber.HouseBillNumber_1.ReferenceValue,'USER-HBL');});
