import test from 'node:test';
import assert from 'node:assert/strict';
import {inttraQualityIssues} from '../lib/inttra-quality.ts';
import {inttraSnapshot} from '../lib/inttra-snapshot.ts';
import {applyManual} from '../lib/manual-extraction.ts';
const f=value=>({value,source:'Original instruction',confidence:1});
test('address and optional cargo corrections preserve source and allow intentional clearing',()=>{const ex={fields:{},containers:[],issues:[],cargoLines:[{description:f('COOKER'),marksAndNumbers:f('OLD'),ncmCode:f('123')}],actualParties:{shipper:{country:f('TR')}}};const out=applyManual(ex,{partyOverrides:{shipper:{country:'GB',street:'New Street'}},cargoOverrides:[{index:0,fields:{marksAndNumbers:'',ncmCode:'',description:'NEW'}}]});assert.equal(out.actualParties.shipper.country.value,'GB');assert.equal(out.actualParties.shipper.street.confidence,1);assert.equal(out.cargoLines[0].marksAndNumbers.value,'');assert.equal(out.cargoLines[0].ncmCode.value,'');assert.equal(ex.cargoLines[0].marksAndNumbers.value,'OLD');assert.equal(ex.actualParties.shipper.country.value,'TR');});
test('actual-party checks are conditional and never truncate addresses',()=>{const ex={cargoLines:[],actualParties:{shipper:{street:f('x'.repeat(71)),city:f('CITY'),country:f('TR')}}};assert.deepEqual(inttraQualityIssues(ex,'0'),[]);const issues=inttraQualityIssues(ex,'2');assert.ok(issues.some(s=>s.includes('70 karakter')));assert.ok(issues.some(s=>s.includes('Gerçek alıcı')));assert.equal(ex.actualParties.shipper.street.value.length,71);});
test('submitted snapshot uses immutable sent data, not new extraction or manual values',()=>{const saved={payload:{ShipmentInstruction:{HouseBillIndicator:'2',SICompanies:{exportSeller:{CompanyName:'Submitted name'}},Containers:[{ContainerNumber:'BOX',ContainerLineItems:[{CargoDescription:'Submitted cargo',LineItemAttrs:{LineItemAttr_1:{LineItemAttrTypeCode:'2',LineItemAttrValue:'123'}},LineItemReferences:{LineItemReference_15:{LineItemReferenceValue:'123'}}}]}]}}};const raw=JSON.stringify(saved);const view=inttraSnapshot('547859763',raw);assert.equal(view.reference,'547859763');assert.equal(view.parties[0].name,'Submitted name');assert.equal(view.cargo[0].description,'Submitted cargo');assert.ok(view.issues.some(s=>s.includes('Ödeme yöntemi')));assert.ok(view.issues.some(s=>s.includes('HS ile NCM')));assert.equal(JSON.stringify(saved),raw);assert.equal(inttraSnapshot('id','bad json'),null);});
