import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import ts from 'typescript';import {createHash} from 'node:crypto';
const uri=s=>'data:text/javascript;base64,'+Buffer.from(ts.transpileModule(s,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022,resolveJsonModule:true}}).outputText).toString('base64');
const reference=uri(fs.readFileSync('lib/inttra-reference.ts','utf8')),options=uri(fs.readFileSync('lib/inttra-options.ts','utf8'));
const mapping=uri(fs.readFileSync('lib/inttra-mapping.ts','utf8').replace("'./inttra-options'",JSON.stringify(options)));
const runtime=uri('export class AppError extends Error {constructor(message, status=400){super(message);this.status=status}};export const db=()=>globalThis.__journalDB;export const digest=async s=>globalThis.__digest(s);');
const quality=uri(fs.readFileSync('lib/inttra-quality.ts','utf8'));
const builderSource=fs.readFileSync('lib/server/inttra-builder.ts','utf8').replace("import emptyForm from '../inttra-empty-form.json';",'const emptyForm='+fs.readFileSync('lib/inttra-empty-form.json','utf8')+';').replace("'../inttra-quality'",JSON.stringify(quality)).replace("'../inttra-mapping'",JSON.stringify(mapping)).replace("'../inttra-reference'",JSON.stringify(reference)).replace("'./runtime'",JSON.stringify(runtime));
const {buildInttraDraft}=await import(uri(builderSource));
test('ENS always uses carrier even when older saved records have blank or self filing',()=>{for(const value of ['',undefined,'0','1','2']){const x=fixture();x.manual.inttra.ensFiler=value;assert.equal(buildInttraDraft(x.ex,x.manual,x.options,x.user,'ens').ShipmentInstruction.EnsFilerIndicator,'2');assert.equal(x.manual.inttra.ensFiler,value);}});
const f=value=>({value,source:'Test instruction',confidence:1});
function fixture(){const fields=Object.fromEntries(['shipper','consignee','notify','mblShipper','mblConsignee','mblNotify'].flatMap(k=>[[k+'Name',f(k+' company')],[k+'Address',f(k+' address')]]));Object.assign(fields,{packageCount:f('2'),grossWeightKg:f('20'),blType:f('SWB')});return {ex:{fields,actualParties:Object.fromEntries(['shipper','consignee','notify'].map(role=>[role,{street:f('Test street'),city:f('Test city'),country:f('TR')}])),containers:[{containerNumber:f('ARKU8360679'),containerType:f('40 HC'),sealNumber:f('SEAL')}],cargoLines:[{containerNumber:f('ARKU8360679'),description:f('Goods'),packageType:f('PACKAGES'),packageCount:f('2'),grossWeightKg:f('20'),hsCode:f('123456')}]},manual:{bookingNumber:'NEW-BOOK',blReference:'NEW-BL',houseBillNumber:'NEW-HBL',vessel:'NEW-VESSEL',voyage:'NEW-VOYAGE',moveType:'1',chargeMode:'individual',charges:[{chargeType:'3',freightTerm:'Collect',payer:'4',paymentLocation:''}],inttra:{carrier:'900\u0001TEST CARRIER',loadPort:'10:TEST:PORT A',dischargePort:'11:TEST:PORT B',origin:'10:TEST:PORT A',destination:'11:TEST:PORT B',issuePlace:'12:TEST:CITY',ensFiler:'2',houseBill:'2',euDelivery:'1',sealType:'1',standardFcl:true,paymentMethod:'D',routeCountries:'TR-GB',documentFreighted:'',documentUnfreighted:'1'}},options:{countriesList:JSON.stringify({content:[{value:'100',code:'TR',label:'TURKEY'}]}),carriersList:JSON.stringify({content:[{label:'TEST CARRIER',value:'900\u0001TEST CARRIER'}]}),containerTypeList:JSON.stringify({content:[{label:'40 High Cube',value:'45G0_0'}]}),packageTypesList:JSON.stringify({content:[{label:'Package',value:'284'}]})},user:{userCompanyID:'100',userCompanyName:'TEST FORWARDER',activityId:'ExportForwarder'}}}
test('INTTRA creates fresh IDs and keeps HBL/MBL parties, actual cargo and chosen codes separate',()=>{const x=fixture(),s=buildInttraDraft(x.ex,x.manual,x.options,x.user,'new-record').ShipmentInstruction;assert.equal(s.SiId,'');assert.equal(s.ShipmentId,'');assert.equal(s.SiName,'CBI-new-record');assert.equal(s.SICompanies.shipper.CompanyName,'mblShipper company');assert.equal(s.SICompanies.exportSeller.CompanyName,'shipper company');assert.equal(s.SIReferences.HouseBillNumber.HouseBillNumber_1.ReferenceValue,'NEW-HBL');assert.equal(s.Containers[0].ContainerSeals.ContainerSeal_1.SealNumber[0],'SEAL');assert.equal(s.Containers[0].ContainerLineItems[0].PackageTypeCode,'284');assert.equal(s.ShipmentSummary.TotalContainerCount,1);assert.equal(s.SICompanies.Requestor.CompanyDocuments.SeaWaybillDocumentNonFreighted.NumberOfDocuments,'1');assert.ok(!JSON.stringify(s).includes('1046336'));});
test('unassigned cargo, unresolved carrier, absent operational choices stop request building',()=>{const x=fixture();assert.throws(()=>buildInttraDraft(x.ex,{...x.manual,inttra:undefined},x.options,x.user,'id'));assert.throws(()=>buildInttraDraft(x.ex,{...x.manual,inttra:{...x.manual.inttra,carrier:'unverified'}},x.options,x.user,'id'));x.ex.cargoLines[0].containerNumber=f('OTHER');assert.throws(()=>buildInttraDraft(x.ex,x.manual,x.options,x.user,'id'));});
test('structured actual-party addresses and countries reach separate platform fields',()=>{const x=fixture();x.ex.actualParties.shipper.postalCode=f('45030');const s=buildInttraDraft(x.ex,x.manual,x.options,x.user,'r').ShipmentInstruction;assert.equal(s.SICompanies.exportSeller.Street,'Test street');assert.equal(s.SICompanies.exportSeller.City,'Test city');assert.equal(s.SICompanies.exportSeller.CountryGeoId,'100');assert.equal(s.SICompanies.exportSeller.Country,'TURKEY');assert.equal(s.SICompanies.exportSeller.Zip,'45030');assert.equal(s.SICompanies.shipper.CompanyAddress,'mblShipper address');});
test('missing actual address, ambiguous country and absent payment method block mapping',()=>{const x=fixture();delete x.ex.actualParties.shipper.city;assert.throws(()=>buildInttraDraft(x.ex,x.manual,x.options,x.user,'r'),/Şehir/);x.ex.actualParties.shipper.city=f('City');x.ex.actualParties.shipper.country=f('UNKNOWN');assert.throws(()=>buildInttraDraft(x.ex,x.manual,x.options,x.user,'r'),/ülkesini/);x.ex.actualParties.shipper.country=f('TR');x.manual.inttra.paymentMethod='';assert.throws(()=>buildInttraDraft(x.ex,x.manual,x.options,x.user,'r'),/ödeme yöntemi/);});
test('separate container references and full descriptions are preserved, HS never becomes NCM',()=>{const x=fixture();const row=x.ex.cargoLines[0];row.description=f('COOKER\nKENWOOD MODEL: KDC60SS25');row.marksAndNumbers=f('REF: M012026000014830\nVES.NO: 4990065865\nPO: 700337');x.ex.containers.push({...x.ex.containers[0],containerNumber:f('TGCU5124739')});x.ex.cargoLines.push({...row,containerNumber:f('TGCU5124739'),marksAndNumbers:f('REF: M012026000014830\nVES.NO: 4990065865\nPO: 700338')});const s=buildInttraDraft(x.ex,x.manual,x.options,x.user,'r').ShipmentInstruction;const a=s.Containers[0].ContainerLineItems[0],b=s.Containers[1].ContainerLineItems[0];assert.equal(a.CargoDescription,row.description.value);assert.match(a.MarksAndNumbers,/700337/);assert.ok(!a.MarksAndNumbers.includes('700338'));assert.match(b.MarksAndNumbers,/700338/);assert.equal(a.LineItemAttrs.LineItemAttr_2.LineItemAttrValue,'123456');assert.equal(a.LineItemReferences.LineItemReference_15,undefined);assert.equal(a.LineItemReferences.LineItemReference_20,undefined);row.ncmCode=f('12345678');row.cusCode=f('1234567-8');const item=buildInttraDraft(x.ex,x.manual,x.options,x.user,'r').ShipmentInstruction.Containers[0].ContainerLineItems[0];assert.equal(item.LineItemReferences.LineItemReference_15.LineItemReferenceValue,'12345678');assert.equal(item.LineItemReferences.LineItemReference_20.LineItemReferenceValue,'1234567-8');});
const store=new Map();globalThis.__digest=s=>createHash('sha256').update(s).digest('hex');globalThis.__journalDB={prepare(sql){return {bind(...a){return {first:async()=>store.get(a.slice(0,4).join('|'))||null,run:async()=>{if(sql.startsWith('INSERT')){const key=a.slice(0,4).join('|');if(store.has(key))return {meta:{changes:0}};store.set(key,{status:'sending',request_hash:a[4]});}else if(sql.includes("status='complete'")){const key=a.slice(2,6).join('|');Object.assign(store.get(key),{status:'complete',result:a[0]});}else if(sql.includes('SET status=?')){const key=a.slice(2,6).join('|');Object.assign(store.get(key),{status:a[0]});}else if(sql.startsWith('DELETE'))store.delete(a.slice(0,4).join('|'));return {meta:{changes:1}}}}}}}};
const {runStep}=await import(uri(fs.readFileSync('lib/server/platform-journal.ts','utf8').replace("'./runtime'",JSON.stringify(runtime))));
test('persisted result is reused without a second platform call; changed request is rejected',async()=>{store.clear();let calls=0;const run={id:'r',revision:1,owner:'o'};assert.equal(await runStep(run,'inttra','submit',{value:1},async()=>{calls++;return 'SI123'}),'SI123');assert.equal(await runStep(run,'inttra','submit',{value:1},async()=>{calls++;return 'wrong'}),'SI123');assert.equal(calls,1);await assert.rejects(runStep(run,'inttra','submit',{value:2},async()=>''));});
test('timeout after sending never retries an ambiguous platform write',async()=>{store.clear();let calls=0;const send=async()=>{calls++;throw Error('timeout')};const run={id:'r',revision:1,owner:'o'};await assert.rejects(runStep(run,'tmaxx','save',{value:1},send));await assert.rejects(runStep(run,'tmaxx','save',{value:1},send));assert.equal(calls,1);});
async function transferHarness({warnings=[],failInttra=false,paused=[],hblRequired}={}){
 const state={deliveries:[{id:'h',platform:'tmaxx',status:'waiting'},{id:'m',platform:'inttra',status:'waiting'}],calls:[],recordStatus:'ready',paused};
 globalThis.__transferPaused=paused;globalThis.__transferMocks={prepareTmaxx:async()=>{state.calls.push('prepare-tmaxx');return {}},prepareInttra:async()=>{state.calls.push('prepare-inttra');return {warnings,approved:false}},executeTmaxx:async()=>{state.calls.push('save-tmaxx');return 'HBL-1'},executeInttra:async()=>{state.calls.push('submit-inttra');if(failInttra)throw Error('Response lost');return 'SI-2'}};
 globalThis.__transferDB={prepare(sql){return {bind(...a){return {first:async()=>null,run:async()=>{if(sql.includes("SET status='sending'"))state.deliveries.find(d=>d.id===a.at(-1)).status='sending';else if(sql.includes("UPDATE deliveries SET status='created'"))Object.assign(state.deliveries.find(d=>d.id===a.at(-1)),{status:'created',reference:a[0]});else if(sql.includes("UPDATE deliveries SET status='unknown'"))state.deliveries.find(d=>d.id===a.at(-1)).status='unknown';else if(sql.includes("SET status='complete'"))state.recordStatus='complete';else if(sql.includes("SET status='review'"))state.recordStatus='review';else if(sql.includes("SET status='partial'"))state.recordStatus='partial';return {meta:{changes:1}}}}}}}};
 const source=fs.readFileSync('lib/server/transfer.ts','utf8').replace("import {platformEnabled} from './platform-policy';",'const platformEnabled=id=>!globalThis.__transferPaused.includes(id);').replace("import {AppError,db,digest} from './runtime';",'class AppError extends Error {};const db=()=>globalThis.__transferDB;const digest=async s=>globalThis.__digest(s);').replace("import {prepareTmaxx,executeTmaxx} from './tmaxx-workflow';",'const {prepareTmaxx,executeTmaxx}=globalThis.__transferMocks;').replace("import {prepareInttra,executeInttra} from './inttra-workflow';",'const {prepareInttra,executeInttra}=globalThis.__transferMocks;')+'\n// unique '+Math.random();
 const {transfer}=await import(uri(source));return {...state,run:()=>transfer({id:'r',owner:'o',revision:1},{hblRequired,fields:{bookingNumber:f('B')},containers:[{containerNumber:f('ARKU8360679')}]},{},state.deliveries),state};
}
test('confirmed position without agent never prepares or writes an HBL',async()=>{const h=await transferHarness({hblRequired:false});await h.run();assert.deepEqual(h.state.calls,['prepare-inttra','submit-inttra']);assert.equal(h.state.recordStatus,'complete');assert.equal(h.state.deliveries[1].reference,'SI-2');});
test('removing agent cannot hide an already created HBL',async()=>{const h=await transferHarness({hblRequired:false});h.state.deliveries[0].status='created';await assert.rejects(h.run(),/Mevcut HBL/);assert.deepEqual(h.state.calls,[]);});
test('only explicitly omitted seals produce an empty seal collection, never a placeholder',()=>{const x=fixture();x.ex.containers[0].sealNumber=f('');assert.throws(()=>buildInttraDraft(x.ex,x.manual,x.options,x.user,'r'),/sealNumber/);x.ex.omittedSeals=['ARKU8360679'];x.manual.inttra.sealType='';const s=buildInttraDraft(x.ex,x.manual,x.options,x.user,'r').ShipmentInstruction;assert.deepEqual(s.Containers[0].ContainerSeals,{});});
test('both preflights finish before writes; both platform references are persisted',async()=>{const h=await transferHarness();await h.run();assert.deepEqual(h.state.calls,['prepare-tmaxx','prepare-inttra','save-tmaxx','submit-inttra']);assert.equal(h.state.recordStatus,'complete');assert.deepEqual(h.state.deliveries.map(d=>d.reference),['HBL-1','SI-2']);});
test('review warning stops both final writes until explicitly approved',async()=>{const h=await transferHarness({warnings:[{code:'10136',message:'Booking not found'}]});await h.run();assert.deepEqual(h.state.calls,['prepare-tmaxx','prepare-inttra']);assert.ok(h.state.deliveries.every(d=>d.status==='waiting'));assert.equal(h.state.recordStatus,'review');});
test('paused T-MAXX never preflights or writes while INTTRA finishes independently',async()=>{const h=await transferHarness({paused:['tmaxx']});await h.run();assert.deepEqual(h.state.calls,['prepare-inttra','submit-inttra']);assert.equal(h.state.deliveries[0].status,'waiting');assert.equal(h.state.deliveries[1].reference,'SI-2');assert.equal(h.state.recordStatus,'partial');});
test('second platform timeout retains first platform success and marks second ambiguous',async()=>{const h=await transferHarness({failInttra:true});await assert.rejects(h.run());assert.deepEqual(h.state.deliveries.map(d=>d.status),['created','unknown']);assert.notEqual(h.state.recordStatus,'complete');});
