'use client';
import type {Fields} from '@/lib/domain';
import type {Manual} from '@/lib/manual';
import {Input} from './ui/input';
const labels={description:'Cargo Description · Mal açıklaması',marksAndNumbers:'Marks & Numbers · İşaretler ve referanslar',packageCount:'Kap adedi',packageType:'Ambalaj türü',grossWeightKg:'Brüt ağırlık (kg)',netWeightKg:'Net ağırlık (kg)',containerNumber:'Konteyner numarası',hsCode:'HS / HTS kodu',ncmCode:'NCM kodu',cusCode:'CUS kodu'};
export function CargoEditor({rows,manual,disabled,showAll,onChange}:{rows:Fields[];manual:Manual;disabled:boolean;showAll:boolean;onChange:(m:Manual)=>void}){
 function update(index:number,key:string,value:string){const previous=manual.cargoOverrides.find(c=>c.index===index);onChange({...manual,cargoOverrides:[...manual.cargoOverrides.filter(c=>c.index!==index),{index,fields:{...previous?.fields,[key]:value}}]});}
 return <details className="form-section" open><summary>Mal kalemleri ve konteyner referansları</summary><p>Her konteynerin açıklamasını ve referanslarını kontrol edin. Kap ve ağırlık ayrı gönderilir. HS, NCM ve CUS birbirinden farklı alanlardır.</p>{rows.map((row,index)=>{const overrides=manual.cargoOverrides.find(c=>c.index===index)?.fields||{};return <section className="cargo-card" key={index}><div className="card-heading"><h4>{row.containerNumber?.value||'Konteyner atanmamış'}</h4><span>Mal kalemi {index+1}</span></div><div className="manual-grid">{(['description','marksAndNumbers','packageCount','packageType','grossWeightKg','hsCode',...(showAll?['netWeightKg','containerNumber','ncmCode','cusCode']:[])] as (keyof typeof labels)[]).map(key=>{const value=overrides[key]??row[key]?.value??'';const multiline=key==='description'||key==='marksAndNumbers';return <label key={key}>{labels[key]}{multiline?<textarea rows={6} disabled={disabled} value={value} maxLength={4000} placeholder={key==='marksAndNumbers'?'Belgedeki REF, VES.NO, PO veya işaret bilgileri':'Belgede bulunamadı'} onChange={e=>update(index,key,e.target.value)}/>:<Input disabled={disabled} value={value} onChange={e=>update(index,key,e.target.value)}/>}</label>})}</div></section>})}</details>;
}
