'use client';
import {useState} from 'react';
import type {Manual} from '@/lib/manual';
import type {Option} from '@/lib/inttra-reference';
import {Button} from './ui/button';
import {Input} from './ui/input';
export const emptyInttra:NonNullable<Manual['inttra']>={standardFcl:false,sealType:'',carrier:'',loadPort:'',dischargePort:'',origin:'',destination:'',issuePlace:'',ensFiler:'',houseBill:'',euDelivery:'',paymentMethod:'',routeCountries:'',documentFreighted:'',documentUnfreighted:''};
function Location({label,value,disabled,onChange}:{label:string;value:string;disabled:boolean;onChange:(v:string)=>void}){
 const [query,setQuery]=useState(''),[options,setOptions]=useState<Option[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 return <div><label>{label}<small>{value?value.split(':').slice(2).join(':'):'Konum seçilmedi'}</small><Input disabled={disabled||loading} value={query} placeholder="Şehir veya liman adı (en az 3 harf)" onChange={e=>setQuery(e.target.value)}/></label><Button variant="outline" disabled={disabled||loading||query.trim().length<3} onClick={async()=>{setLoading(true);setError('');try{const r=await fetch('/api/platform-options?q='+encodeURIComponent(query));const d=await r.json() as {error?:string;locations:Option[];carriers:Option[]};if(!r.ok)throw Error(d.error);setOptions(d.locations);if(!d.locations.length)setError('Konum bulunamadı.');}catch(e){setError((e as Error).message)}finally{setLoading(false)}}}>{loading?'Aranıyor…':'Konum bul'}</Button>{options.length>0&&<select aria-label={label+' sonuçları'} disabled={disabled} value={value} onChange={e=>onChange(e.target.value)}><option value="">Sonuçlardan seçin</option>{options.map(o=><option value={o.value} key={o.value}>{o.label}</option>)}</select>}{error&&<p role="alert">{error}</p>}</div>
}
export function InttraSettings({value,disabled,onChange}:{value:Manual['inttra'];disabled:boolean;onChange:(v:NonNullable<Manual['inttra']>)=>void}){
 const m={...emptyInttra,...value};const [carriers,setCarriers]=useState<Option[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 const set=(key:string,v:string|boolean)=>onChange({...m,[key]:v});
 return <details><summary>INTTRA taşıyıcı ve gönderim seçenekleri</summary><p>Bu seçimler INTTRA’ya gönderilecek talimat içindir. Otomatik bir seçim yapılmaz.</p><Button variant="outline" disabled={disabled||loading} onClick={async()=>{setLoading(true);setError('');try{const r=await fetch('/api/platform-options');const d=await r.json() as {error?:string;locations:Option[];carriers:Option[]};if(!r.ok)throw Error(d.error);setCarriers(d.carriers)}catch(e){setError((e as Error).message)}finally{setLoading(false)}}}>{loading?'Yükleniyor…':'INTTRA taşıyıcılarını getir'}</Button>{error&&<p role="alert">{error}</p>}<label>Taşıyıcı<select disabled={disabled} value={m.carrier} onChange={e=>set('carrier',e.target.value)}><option value="">Seçin</option>{m.carrier&&!carriers.some(c=>c.value===m.carrier)&&<option value={m.carrier}>{m.carrier.split('\u0001')[1]||'Kayıtlı taşıyıcı'}</option>}{carriers.map(c=><option key={c.value} value={c.value}>{c.label}</option>)}</select></label><div className="manual-grid">{([['loadPort','Yükleme limanı'],['dischargePort','Boşaltma limanı'],['origin','Malın çıkış yeri'],['destination','Nihai teslim yeri'],['issuePlace','Belge düzenleme yeri']] as const).map(([key,label])=><Location key={key} label={label} value={m[key]} disabled={disabled} onChange={v=>set(key,v)}/>)}</div><div className="manual-grid">{([
 ['sealType','Mühür sahibi',[['1','Taşıyıcı'],['3','Gönderen']]],
 ['euDelivery','Teslim bölgesi',[['1','Diğer ülkeler'],['2','AB ülkeleri'],['3','ABD / Kanada'],['4','Birleşik Arap Emirlikleri']]],
 ['ensFiler','ENS beyanını kim yapacak?',[['0','Uygulanmıyor'],['2','Taşıyıcı'],['1','Kendimiz']]],
 ['houseBill','House Bill kapsamı',[['0','House Bill yok'],['2','Tek House Bill — HBL taraflarını kullan']]],
 ['paymentMethod','Ödeme yöntemi',[['Y','Taşıyıcı hesabı'],['H','Elektronik transfer'],['Z','Peşin ödenmedi'],['D','Diğer'],['A','Nakit'],['C','Çek'],['B','Kredi kartı']]]
 ] as const).map(([key,label,options])=><label key={key}>{label}<select disabled={disabled} value={m[key]} onChange={e=>set(key,e.target.value)}><option value="">Seçin</option>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>)}{([['routeCountries','Ülke rotası (örnek: TR-GB)'],['documentFreighted','Navlun gösterilen belge adedi'],['documentUnfreighted','Navlun gösterilmeyen belge adedi']] as const).map(([key,label])=><label key={key}>{label}<Input disabled={disabled} maxLength={key==='routeCountries'?200:2} value={m[key]} onChange={e=>set(key,e.target.value)}/></label>)}</div><label><input type="checkbox" disabled={disabled} checked={m.standardFcl} onChange={e=>set('standardFcl',e.target.checked)}/> Bu yük FCL’dir ve konteynerler taşıyıcı tarafından sağlanır.</label></details>
}
