'use client';
import {moveTypes,chargeTypes,payerTypes} from '@/lib/inttra-options';
import {useState} from 'react';
import {emptyManual,Manual} from '@/lib/manual';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
export function ManualInstructions({value,disabled,onSave}:{value:Manual|null;disabled:boolean;onSave:(m:Manual)=>Promise<void>}){
 const [m,set]=useState<Manual>(value||structuredClone(emptyManual));
 const update=(key:string,value:string)=>set(m=>({...m,[key]:value}));
 return <section className="manual-instructions"><h3>INTTRA bilgileri</h3><p>Belgeleri tamamlayan bilgileri girin. Masrafları ve Move Type seçimini siz belirleyin.</p><div className="manual-grid">{[['bookingNumber','Carrier Booking Number'],['blReference','B/L Reference Number'],['vessel','Vessel'],['voyage','Voyage'],['moveType','Move Type']].map(([key,label])=><label key={key}>{label}{key==='moveType'?<select disabled={disabled} value={m.moveType} onChange={e=>update(key,e.target.value)}><option value="">Seçin</option>{moveTypes.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:<Input disabled={disabled} maxLength={200} value={m[key as keyof Manual] as string} onChange={e=>update(key,e.target.value)}/>}</label>)}</div><h4>Freight Charges</h4><label>Ödeme kapsamı<select disabled={disabled} value={m.chargeMode} onChange={e=>set({...m,chargeMode:e.target.value as Manual['chargeMode'],charges:e.target.value==='all'?[m.charges[0]||{chargeType:'',freightTerm:'',payer:'',paymentLocation:''}]:m.charges})}><option value="">Seçin</option><option value="all">All Charges</option><option value="individual">Individual Charges</option></select></label>{m.charges.map((r,i)=><div className="charge-row" key={i}>{(['chargeType','freightTerm','payer','paymentLocation'] as const).map(key=><label key={key}>{({chargeType:'Charge Type',freightTerm:'Freight Term',payer:'Payer',paymentLocation:'Payment Location'})[key]}{(key==='chargeType'&&m.chargeMode!=='all')||key==='payer'?<select disabled={disabled} value={r[key]} onChange={e=>set({...m,charges:m.charges.map((x,n)=>n===i?{...x,[key]:e.target.value}:x)})}><option value="">Seçin</option>{(key==='chargeType'?chargeTypes:payerTypes).map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:key==='freightTerm'?<select disabled={disabled} value={r[key]} onChange={e=>set({...m,charges:m.charges.map((x,n)=>n===i?{...x,freightTerm:e.target.value as typeof r.freightTerm}:x)})}><option value="">Seçin</option><option>Prepaid</option><option>Collect</option></select>:<Input disabled={disabled||(key==='chargeType'&&m.chargeMode==='all')} maxLength={200} value={key==='chargeType'&&m.chargeMode==='all'?'All Charges':r[key]} onChange={e=>set({...m,charges:m.charges.map((x,n)=>n===i?{...x,[key]:e.target.value}:x)})}/>}</label>)}<Button variant="outline" disabled={disabled} onClick={()=>set({...m,charges:m.charges.filter((_,n)=>n!==i)})}>Satırı sil</Button></div>)}<div className="detail-actions"><Button variant="outline" disabled={disabled||m.charges.length>=20||(m.chargeMode==='all'&&m.charges.length===1)} onClick={()=>set({...m,charges:[...m.charges,{chargeType:'',freightTerm:'',payer:'',paymentLocation:''}]})}>Masraf satırı ekle</Button><Button disabled={disabled} onClick={()=>onSave(m)}>Kaydet ve kontrol et</Button></div></section>
}
