export const fieldNames=['description','packageCount','packageType','netWeightKg','grossWeightKg','volumeM3','bookingNumber','shipperName','shipperAddress','consigneeName','consigneeAddress','notifyName','notifyAddress','mblShipperName','mblShipperAddress','mblConsigneeName','mblConsigneeAddress','mblNotifyName','mblNotifyAddress','loadPort','dischargePort','vessel','voyage','containerNumber','containerType','sealNumber','hsCode','freightPayment','blType','reference'] as const;
export type Field={value:string|null;source:string;confidence:number};
export type Fields=Record<string,Field>;
export type Extraction={fields:Fields;issues:string[];documentType:string;containerCount:number;cargoLineCount:number;containers:Fields[];cargoLines:Fields[];actualParties?:Partial<Record<'shipper'|'consignee'|'notify',Fields>>;schemaVersion?:number;hblRequired?:boolean;omittedSeals?:string[]};
export const names:Record<string,string>={description:'Mal tanımı',packageCount:'Kap adedi',packageType:'Ambalaj türü',grossWeightKg:'Brüt ağırlık',netWeightKg:'Net ağırlık',bookingNumber:'Booking numarası',shipperName:'HBL gönderen',shipperAddress:'HBL gönderen adresi',consigneeName:'HBL alıcı',consigneeAddress:'HBL alıcı adresi',notifyName:'HBL notify',notifyAddress:'HBL notify adresi',mblShipperName:'MBL gönderen',mblShipperAddress:'MBL gönderen adresi',mblConsigneeName:'MBL alıcı',mblConsigneeAddress:'MBL alıcı adresi',mblNotifyName:'MBL notify',mblNotifyAddress:'MBL notify adresi',loadPort:'Yükleme limanı',dischargePort:'Boşaltma limanı',vessel:'Gemi',voyage:'Sefer',containerNumber:'Konteyner numarası',containerType:'Konteyner tipi',sealNumber:'Mühür numarası',hsCode:'HS kodu',freightPayment:'Navlun ödeme',blType:'Belge tipi'};
export const minimumFields=['description','packageCount','packageType','grossWeightKg','bookingNumber','shipperName','shipperAddress','consigneeName','consigneeAddress','notifyName','notifyAddress','mblShipperName','mblShipperAddress','mblConsigneeName','mblConsigneeAddress','mblNotifyName','mblNotifyAddress','loadPort','dischargePort','vessel','voyage','containerNumber','containerType','sealNumber','freightPayment','blType'];
export function containerValid(raw:string){const s=raw.replace(/[\s-]/g,'').toUpperCase();if(!/^[A-Z]{3}[UJZ][0-9]{7}$/.test(s))return false;let sum=0;for(let i=0;i<10;i++){let n=Number(s[i]);if(i<4){const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ';const index=alphabet.indexOf(s[i]);n=10+index+Math.floor((index+9)/10);}sum+=n*2**i;}return (sum%11)%10===Number(s[10]);}
export function validate(ex:Extraction,required=minimumFields){const errors=[...ex.issues];const f=ex.fields;for(const key of new Set(required)){if(key==='sealNumber'&&ex.containers.length===1&&ex.omittedSeals?.includes(ex.containers[0].containerNumber?.value||''))continue;if(ex.containerCount>1&&['containerNumber','containerType','sealNumber'].includes(key))continue;const v=f[key];if(!v?.value?.trim())errors.push(`${names[key]||key}: belgede bulunamadı.`);else if(v.confidence<.95||!v.source.trim())errors.push(`${names[key]||key}: kaynak veya okuma kesinliği yeterli değil.`)}
 if(ex.documentType!=='instruction')errors.push('Yüklenen belge talimat olarak doğrulanamadı. Müşteri talimatını yükleyin.');
 if(ex.containerCount!==ex.containers.length||ex.cargoLineCount!==ex.cargoLines.length)errors.push('Konteyner veya mal kalemi sayısı satırlarla eşleşmiyor.');
 for(const [i,c] of ex.containers.entries()){for(const key of ['containerNumber','containerType','sealNumber']){if(key==='sealNumber'&&ex.omittedSeals?.includes(c.containerNumber?.value||''))continue;if(!c[key]?.value||!c[key].source||c[key].confidence<.95)errors.push(`Konteyner ${i+1}: ${names[key]} eksik veya belirsiz.`);}if(c.containerNumber?.value&&!containerValid(c.containerNumber.value))errors.push(`Konteyner ${i+1}: numara kontrolü başarısız.`)}
 for(const [i,c] of ex.cargoLines.entries()){for(const key of ['description','packageCount','packageType','grossWeightKg'])if(!c[key]?.value||!c[key].source||c[key].confidence<.95)errors.push(`Mal kalemi ${i+1}: ${names[key]} eksik veya belirsiz.`)}
 for(const [i,c] of ex.cargoLines.entries()){
  for(const key of ['packageCount','grossWeightKg','netWeightKg']){const v=c[key]?.value;if(v!=null&&(!/^\d+(\.\d+)?$/.test(v)||Number(v)<=0||(key==='packageCount'&&!Number.isInteger(Number(v)))))errors.push(`Mal kalemi ${i+1}: ${names[key]} pozitif ve geçerli sayı olmalı.`);}
  if(c.netWeightKg?.value&&c.grossWeightKg?.value&&Number(c.netWeightKg.value)>Number(c.grossWeightKg.value))errors.push(`Mal kalemi ${i+1}: net ağırlık brütten büyük olamaz.`);
  if(c.containerNumber?.value&&!ex.containers.some(x=>x.containerNumber?.value===c.containerNumber.value))errors.push(`Mal kalemi ${i+1}: konteyner yük listesinde bulunamadı.`);
 }
 const num=(key:string)=>{const raw=f[key]?.value;if(raw==null)return null;if(!/^\d+(\.\d+)?$/.test(raw)){errors.push(`${names[key]||key}: sayısal biçim belirsiz.`);return null;}return Number(raw)};
 const gross=num('grossWeightKg'),net=num('netWeightKg'),count=num('packageCount');if(gross!==null&&gross<=0)errors.push('Brüt ağırlık sıfırdan büyük olmalı.');if(net!==null&&net<=0)errors.push('Net ağırlık sıfırdan büyük olmalı.');if(gross!==null&&net!==null&&net>gross)errors.push('Net ağırlık brüt ağırlıktan büyük olamaz.');if(count!==null&&(!Number.isInteger(count)||count<=0))errors.push('Kap adedi pozitif bir tam sayı olmalı.');
 if(f.containerNumber?.value&&!containerValid(f.containerNumber.value))errors.push('Konteyner numarası veya kontrol basamağı geçersiz.');if(f.description?.value&&/(NO\. OF PACKAGES|NET WEIGHT|GROSS WEIGHT|KG NET|KG BRÜT)/i.test(f.description.value))errors.push('Mal tanımı ağırlık veya ambalaj alanları içeriyor. Ayrıştırma doğrulanmalı.');for(const k of ['shipperAddress','consigneeAddress','notifyAddress','mblShipperAddress','mblConsigneeAddress','mblNotifyAddress'])if(/\.\.\.|…/.test(f[k]?.value||''))errors.push(`${names[k]}: adres yarım veya kısaltılmış.`);const uniqueContainers=ex.containers.map(c=>c.containerNumber?.value?.replace(/[\s-]/g,'').toUpperCase()).filter(Boolean);if(new Set(uniqueContainers).size!==uniqueContainers.length)errors.push('Aynı konteyner birden fazla kez listelenmiş.');
 for(const key of ['packageCount','grossWeightKg','netWeightKg']){const rows=ex.cargoLines.map(c=>c[key]?.value);if(rows.length&&rows.every(v=>v!=null&&/^\d+(\.\d+)?$/.test(v))&&f[key]?.value&&Math.abs(rows.reduce((sum,v)=>sum+Number(v),0)-Number(f[key].value))>.001)errors.push(`${names[key]} toplamı mal kalemleriyle eşleşmiyor.`);}
 return [...new Set(errors)]}
export function overall(deliveries:{status:string}[]){if(deliveries.length&&deliveries.every(d=>d.status==='created'))return 'complete';if(deliveries.some(d=>d.status==='unknown'||d.status==='sending'))return 'unknown';if(deliveries.some(d=>d.status==='failed'))return 'failed';return 'blocked'}
