import type {Manual} from './manual';
import {chargeTypes,moveTypes,payerTypes} from './inttra-options';
export function mapInttraManual(m:Manual,locations:Record<string,{id:string;country:string;label:string}>={}){
 const move=moveTypes.find(x=>x.value===m.moveType);if(!move)throw Error('Move Type seçilmeli.');
 if(!m.bookingNumber||!m.blReference||!m.vessel||!m.voyage)throw Error('INTTRA booking, B/L, gemi ve sefer alanları gerekli.');
 if(!['individual','all'].includes(m.chargeMode))throw Error('Ödeme kapsamı seçilmeli.');if(m.chargeMode==='all'&&m.charges.length!==1)throw Error('All Charges için tek satır gerekli.');
 if(!m.charges.length)throw Error('Masraf satırı gerekli.');
 const payment:Record<string,unknown>=Object.fromEntries(m.charges.map((r,i)=>{const charge=m.chargeMode==='all'?{value:'6',label:'All Charges'}:chargeTypes.find(x=>x.value===r.chargeType),payer=payerTypes.find(x=>x.value===r.payer);if(!charge||!payer||!['Prepaid','Collect'].includes(r.freightTerm))throw Error('Masraf satırındaki seçimler doğrulanmalı.');if(r.paymentLocation&&!locations[r.paymentLocation])throw Error('Payment Location için platform konum kodu doğrulanmalı.');const loc=locations[r.paymentLocation];return [m.chargeMode==='all'?'ALLCharges':'IndividualCharges_'+i,{ChargeTypeDesc:charge.label,FreightTermCode:r.freightTerm==='Prepaid'?'2':'1',PartyTypeCode:payer.value,ChargeTypeCode:charge.value,LocationCountry:loc?.country||'',GeographyAreaId:loc?.id||'',PartyName:payer.label,PaymentLocation:loc?.label||'',FreightTermDesc:r.freightTerm,PaymentInstructionId:''}]}));
 const reference=(value:string,code:string,description:string)=>({ReferenceTypeDescription:description,ReferenceId:'',ExpirationDate:'',ReferenceValue:value,ReferenceTypeCode:code,IssuanceDate:''});
 return {Vessel:m.vessel,Voyage:m.voyage,MoveTypeCode:move.value,MoveTypeDesc:move.label,PaymentInstructions:payment,SIReferences:{...(m.houseBillNumber?{HouseBillNumber:{HouseBillNumber_1:reference(m.houseBillNumber,'16','House Bill of Ladding Number')}}:{}),CarrierBookingNumber:{CarrierBookingNumber_1:reference(m.bookingNumber,'4','Carrier Booking Reference')},BLReferenceNumber:{BLReferenceNumber_1:reference(m.blReference,'8','Bill Of Lading Reference')}}};
}
