import {moveTypes,chargeTypes,payerTypes} from './inttra-options';
import {z} from 'zod';
import {fieldNames} from './domain';
import {addressKeys,cargoKeys} from './inttra-quality';
const text = z.string().trim().max(200);
export const manualSchema = z.object({ partyOverrides: z.record(z.enum(['shipper',
'consignee',
'notify']),
z.record(z.enum(addressKeys),
z.string().trim().max(200))).default({}),
tmaxxReference: text.default(''),
inttra: z.object({ standardFcl: z.boolean(),
sealType: z.enum(['',
'1',
'3']),
carrier: text,
loadPort: text,
dischargePort: text,
issuePlace: text,
origin: text,
destination: text,
ensFiler: z.enum(['',
'0',
'1',
'2']),
houseBill: z.enum(['',
'0',
'2']),
euDelivery: z.enum(['',
'1',
'2',
'3',
'4']),
paymentMethod: z.enum(['',
'Y',
'H',
'Z',
'D',
'A',
'C',
'B']),
routeCountries: text,
documentFreighted: z.string().regex(/^$|^\d{1,2}$/),
documentUnfreighted: z.string().regex(/^$|^\d{1,2}$/) }).strict().optional(),
houseBillNumber: text.default(''),
cargoOverrides: z.array(z.object({ index: z.number().int().min(0).max(999),
fields: z.record(z.enum(cargoKeys),
z.string().trim().max(4000)) }).strict()).max(1000).default([]),
fieldOverrides: z.record(z.enum(fieldNames),
z.string().trim().max(4000)).default({}),
containerOverrides: z.array(z.object({ containerNumber: text,
containerType: text,
sealNumber: text,
omitSeal: z.boolean().optional() }).strict()).max(100).default([]),
bookingNumber: text,
blReference: text,
vessel: text,
voyage: text,
moveType: text.refine(v => !v || moveTypes.some(o => o.value === v)),
chargeMode: z.enum(['',
'all',
'individual']),
charges: z.array(z.object({ chargeType: text.refine(v => !v || chargeTypes.some(o => o.value === v)),
freightTerm: z.enum(['',
'Prepaid',
'Collect']),
payer: text.refine(v => !v || payerTypes.some(o => o.value === v)),
paymentLocation: text }).strict()).max(20) }).strict();
export type Manual = z.infer<typeof manualSchema>;
export const emptyManual: Manual = { partyOverrides: {},
tmaxxReference: '',
houseBillNumber: '',
cargoOverrides: [],
fieldOverrides: {},
containerOverrides: [],
bookingNumber: '',
blReference: '',
vessel: '',
voyage: '',
moveType: '',
chargeMode: '',
charges: [] };
export function manualIssues(m: Manual) { const issues: string[] = []; for (const [key,
label] of [['bookingNumber',
'Carrier Booking Number'],
['blReference',
'B/L Reference Number'],
['vessel',
'Vessel'],
['voyage',
'Voyage'],
['moveType',
'Move Type'],
['chargeMode',
'Freight Charges seçimi']] as const)
    if (!m[key])
        issues.push(`INTTRA: ${label} alanını doldurun.`); if (!m.charges.length)
    issues.push('INTTRA: en az bir Freight Charges satırı girin.'); if (m.chargeMode === 'all' && m.charges.length !== 1)
    issues.push('INTTRA: All Charges için tek ödeme satırı girin.'); m.charges.forEach((r,
i) => { if ((m.chargeMode === 'individual' && !r.chargeType) || !r.freightTerm || !r.payer)
    issues.push(`INTTRA: masraf satırı ${i + 1} için tür,
ödeme koşulu ve ödeyen tarafı tamamlayın.`); }); const settings = m.inttra; for (const [key,
label] of [['carrier',
'Taşıyıcı'],
['loadPort',
'Yükleme limanı'],
['dischargePort',
'Boşaltma limanı'],
['issuePlace',
'Belge düzenleme yeri'],
['origin',
'Malın çıkış yeri'],
['destination',
'Nihai teslim yeri'],
['ensFiler',
'ENS beyanı'],
['houseBill',
'House Bill kapsamı'],
['euDelivery',
'Teslim bölgesi'],
['sealType',
'Mühür sahibi'],
['paymentMethod',
'Ödeme yöntemi']] as const)
    if (!settings?.[key] && !(key==='sealType'&&m.containerOverrides?.length>0&&m.containerOverrides.every(c=>c.omitSeal)))
        issues.push('INTTRA: ' + label + ' seçimini tamamlayın.'); if (!settings?.standardFcl)
    issues.push('INTTRA: FCL ve taşıyıcı konteyneri seçimini doğrulayın.'); if (!settings?.documentFreighted && !settings?.documentUnfreighted)
    issues.push('INTTRA: istenen belge adedini girin.'); if (settings?.houseBill === '2' && !m.houseBillNumber)
    issues.push('INTTRA: House Bill Number alanını doldurun.'); return issues; }
