// Fixed destination SSO flow observed in INTTRA's own login application.
const allowedHosts=new Set(['api.inttra.com','api.inttra.e2open.com','my.inttra.e2open.com']);
export async function startInttraSession(data,request=fetch){
 if(typeof data.access_token!=='string'||!data.access_token)throw Error('Missing INTTRA token');
 const jar=[];
 for(const domain of ['inttra.com','inttra.e2open.com'])for(const [name,value] of [['TOKEN',data.access_token],['SCOPE',data.scope||'']])jar.push({name,value:encodeURIComponent(value),domain,path:'/'});
 function cookie(url){const u=new URL(url);return jar.filter(c=>(u.hostname===c.domain||u.hostname.endsWith('.'+c.domain))&&(u.pathname===c.path||u.pathname.startsWith(c.path.endsWith('/')?c.path:c.path+'/'))).map(c=>c.name+'='+c.value).join('; ')}
 function store(r,url){const hostname=new URL(url).hostname;for(const line of r.headers.getSetCookie()){const [pair,...attrs]=line.split(';');const eq=pair.indexOf('=');if(eq<1)continue;const c={name:pair.slice(0,eq),value:pair.slice(eq+1),domain:hostname,path:'/'};let expired=false;for(const attr of attrs){const i=attr.indexOf('=');const k=(i<0?attr:attr.slice(0,i)).trim().toLowerCase(),v=i<0?'':attr.slice(i+1).trim();if(k==='domain')c.domain=v.replace(/^\./,'').toLowerCase();if(k==='path')c.path=v||'/';if(k==='max-age'&&Number(v)<=0)expired=true;if(k==='expires'&&Date.parse(v)<Date.now())expired=true}if(!(hostname===c.domain||hostname.endsWith('.'+c.domain))||!['inttra.com','e2open.com'].some(d=>c.domain===d||c.domain.endsWith('.'+d)))continue;const i=jar.findIndex(x=>x.name===c.name&&x.domain===c.domain&&x.path===c.path);if(i>=0)jar.splice(i,1);if(!expired)jar.push(c)}}
 let url='https://api.inttra.com/auth/login?authorization='+encodeURIComponent(data.access_token)+'&syncdomain=true&redirectUrl='+encodeURIComponent(Buffer.from('https://my.inttra.e2open.com/dashboard').toString('base64'));
 let ended=false;for(let i=0;i<8;i++){const u=new URL(url);if(u.protocol!=='https:'||!allowedHosts.has(u.hostname))throw Error('Unexpected SSO redirect');const r=await request(url,{headers:{Cookie:cookie(url)},redirect:'manual',signal:AbortSignal.timeout(20000)});store(r,url);if(r.status>=300&&r.status<400&&r.headers.get('location'))url=new URL(r.headers.get('location'),url).toString();else{if(!r.ok)throw Error('SSO failed');ended=true;break}}
 if(!ended)throw Error('SSO redirect limit');
 const endpoint='https://ship.inttra.e2open.com/siact/createPageParams';const r=await request(endpoint,{method:'POST',headers:{Cookie:cookie(endpoint),'Content-Type':'application/json;charset=UTF-8',Origin:'https://ship.inttra.e2open.com',Referer:'https://ship.inttra.e2open.com/siact/create'},body:'null',redirect:'manual',signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error('INTTRA web session rejected');store(r,endpoint);const options=await r.json();if(!options.moveTypeList||!options.carriersList)throw Error('INTTRA web session not verified');return {cookie:cookie(endpoint),options};
}
